import { z } from "zod";

/**
 * Password policy: at least 12 characters, including uppercase, lowercase,
 * a digit, and a symbol. Message text matches the design handoff exactly.
 */
export const PASSWORD_POLICY_MESSAGE =
  "Your password must be at least 12 characters and include uppercase letters, lowercase letters, numbers, and symbols.";

export const passwordSchema = z
  .string()
  .min(12, PASSWORD_POLICY_MESSAGE)
  .refine((value) => /[a-z]/.test(value), PASSWORD_POLICY_MESSAGE)
  .refine((value) => /[A-Z]/.test(value), PASSWORD_POLICY_MESSAGE)
  .refine((value) => /[0-9]/.test(value), PASSWORD_POLICY_MESSAGE)
  .refine((value) => /[^a-zA-Z0-9]/.test(value), PASSWORD_POLICY_MESSAGE);

export const emailSchema = z.string().trim().min(1).email().max(320);

export const displayNameSchema = z.string().trim().min(1).max(255);

export const registerSchema = z
  .object({
    email: emailSchema,
    password: passwordSchema,
    displayName: displayNameSchema,
    // Gates account creation: registration is no longer open to anyone,
    // only to holders of a valid, unconsumed token generated by someone
    // with registration_token.manage in some workspace (see
    // registration-token.service.ts). Does NOT grant any workspace
    // membership by itself.
    registrationToken: z.string().min(1),
  })
  .strict();
export type RegisterInput = z.infer<typeof registerSchema>;

export const loginSchema = z
  .object({
    email: emailSchema,
    password: z.string().min(1),
  })
  .strict();
export type LoginInput = z.infer<typeof loginSchema>;

export const setupSchema = z
  .object({
    email: emailSchema,
    password: passwordSchema,
    displayName: displayNameSchema,
  })
  .strict();
export type SetupInput = z.infer<typeof setupSchema>;

export const requestPasswordResetSchema = z
  .object({
    email: emailSchema,
  })
  .strict();
export type RequestPasswordResetInput = z.infer<typeof requestPasswordResetSchema>;

export const confirmPasswordResetSchema = z
  .object({
    token: z.string().min(1),
    password: passwordSchema,
  })
  .strict();
export type ConfirmPasswordResetInput = z.infer<typeof confirmPasswordResetSchema>;

export const changeEmailSchema = z
  .object({
    // Not passwordSchema: an existing password may predate the current
    // policy, so re-authentication must not re-validate it against today's
    // rules (mirrors loginSchema's password field exactly).
    currentPassword: z.string().min(1),
    newEmail: emailSchema,
  })
  .strict();
export type ChangeEmailInput = z.infer<typeof changeEmailSchema>;

export const changePasswordSchema = z
  .object({
    currentPassword: z.string().min(1),
    newPassword: passwordSchema,
  })
  .strict();
export type ChangePasswordInput = z.infer<typeof changePasswordSchema>;

// Self-service account deletion (soft-delete — see account.service.ts#deleteAccount).
// Re-authentication mirrors changeEmailSchema/changePasswordSchema exactly:
// not passwordSchema, since an existing password may predate the current
// policy.
export const deleteAccountSchema = z
  .object({
    currentPassword: z.string().min(1),
  })
  .strict();
export type DeleteAccountInput = z.infer<typeof deleteAccountSchema>;
